spring:
  profiles:
    active:
  datasource:
    url: jdbc:mysql://localhost:3306/zenela?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
    username: root
    password: root1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10200MB
      max-request-size: 10500MB

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
cloud:
  aws:
    credentials:
      access-key: AKIAZHZ2SIS5JSYYJ24O
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false